apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
  labels:
    app: gateway
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
      - name: gateway
        image: leonardosartorello/java-gateway-k8s:v3
        ports:
        - containerPort: 80
        env:
        - name: SERVER_HOST
          valueFrom:
            configMapKeyRef:
              name: dados
              key: SERVER_HOST
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pagamentos
  labels:
    app: pagamentos
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pagamentos
  template:
    metadata:
      labels:
        app: pagamentos
    spec:
      hostname: pagamentos-ms
      containers:
      - name: pagamentos
        image: leonardosartorello/java-pagamentos-k8s:v3
        ports:
        - containerPort: 4000
        env:
        - name: SERVER_HOST
          valueFrom:
            configMapKeyRef:
              name: dados
              key: SERVER_HOST
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: dados
              key: DB_HOST
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: senhas
              key: DB_USER
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: senhas
              key: DB_PASSWORD
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pedidos
  labels:
    app: pedidos
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pedidos
  template:
    metadata:
      labels:
        app: pedidos
    spec:
      hostname: pedidos-ms
      containers:
      - name: pedidos
        image: leonardosartorello/java-pedidos-k8s:v3
        ports:
        - containerPort: 40001
        env:
        - name: SERVER_HOST
          valueFrom:
            configMapKeyRef:
              name: dados
              key: SERVER_HOST
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: dados
              key: DB_HOST
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: senhas
              key: DB_USER
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: senhas
              key: DB_PASSWORD
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: server
spec:
  selector:
    matchLabels:
      app: server
  serviceName: "server"
  replicas: 2
  minReadySeconds: 10
  template:
    metadata:
      labels:
        app: server
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: server
        image: leonardosartorello/java-server-k8s:v3
        ports:
        - containerPort: 8081
          name: server
        env:
        - name: SERVER_HOST
          valueFrom:
            configMapKeyRef:
              name: dados
              key: SERVER_HOST